services:
  db:
    build: .
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: playThis
      DATABASE: ${DATABASE}
      DB_PORT: 5432
    ports:
      - "5432:5432"